[fix] using git to detect branch instead of ci (failed for tags)
Former-commit-id: c18153a34ebee0f0929ba282fa500c74b3d61b37

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -13,7 +13,11 @@ stages:
 # # provides a variable "GIT_SUBMODULE_STRATEGY" that sets up submodules automatically
 # # But then branch tracking doesn't work (doesn't seem to allow for specifying the --remote) flag
 .prepare_repo: &prepare_repo |
-  git clone --branch ${CI_COMMIT_BRANCH} https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.uib.gmbh/uib/opsiweb-ui-components.git opsiweb/uib-components
+  echo "CIC_Branch ${CI_COMMIT_BRANCH}"
+  echo "GIT_Branch ${git symbolic-ref --short HEAD || echo "develop"}"
+  # git clone --branch ${CI_COMMIT_BRANCH} https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.uib.gmbh/uib/opsiweb-ui-components.git opsiweb/uib-components
+  # Testing using current branch (othewise job failes on "tag"-execution)
+  git clone --branch ${git symbolic-ref --short HEAD || echo "develop"} https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.uib.gmbh/uib/opsiweb-ui-components.git opsiweb/uib-components
   cd opsiweb/uib-components
   git branch -a
   ls -lah
