[fix] remove gitrelease job
Former-commit-id: 62c26d219b9c1933575b919d14feffe926827d91

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -646,46 +646,46 @@ upload:gittag:
 ######################################################################### publish
 #########################################################################
 
-.push_release: &push_release |
-  # post release
-  echo "ProjectURL: $CI_API_V4_URL"
-  echo "ProjectID: $CI_PROJECT_ID"
-  LTAG=$(git describe --tags --abbrev=0 || git tag) # latest tag
-  echo "ProjectTAG: $TAG"
-  printf "ProjectMSG: \n$(cat $FILE)\n"
-  http_response=$(curl --request POST \
-    -o response.txt \
-    --fail-with-body \
-    --header "PRIVATE-TOKEN: $TOKEN_SUCHER" \
-    --url "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases?tag_name=$TAG&ref=main" \
-    --data-urlencode "message=$(cat $FILE)" )
+# .push_release: &push_release |
+#   # post release
+#   echo "ProjectURL: $CI_API_V4_URL"
+#   echo "ProjectID: $CI_PROJECT_ID"
+#   LTAG=$(git describe --tags --abbrev=0 || git tag) # latest tag
+#   echo "ProjectTAG: $TAG"
+#   printf "ProjectMSG: \n$(cat $FILE)\n"
+#   http_response=$(curl --request POST \
+#     -o response.txt \
+#     --fail-with-body \
+#     --header "PRIVATE-TOKEN: $TOKEN_SUCHER" \
+#     --url "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases?tag_name=$TAG&ref=main" \
+#     --data-urlencode "message=$(cat $FILE)" )
 
-  echo "$http_response: $(cat response.txt)"
-  if [ "$http_response" != "200" ]; then echo "$http_response: $(cat response.txt)"; exit $http_response; fi
-  echo ""
+#   echo "$http_response: $(cat response.txt)"
+#   if [ "$http_response" != "200" ]; then echo "$http_response: $(cat response.txt)"; exit $http_response; fi
+#   echo ""
 
-upload:git:
-  stage: upload
-  image: registry.gitlab.com/gitlab-org/release-cli:latest
-  needs:
-    - job: build:zip
-      artifacts: true
-  rules:
-    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
-  script:
-    - echo "Create Release $TAG, $CI_COMMIT_TAG, $JOB_ID"
-  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
-    tag_name: '$CI_COMMIT_TAG'
-    description: '$CI_COMMIT_TAG'
-  release:
-    name: 'Release $CI_COMMIT_TAG'
-    tag_name: '$CI_COMMIT_TAG'
-    ref: '$CI_COMMIT_TAG'
-    description: 'Release $CI_COMMIT_TAG'
-    assets:
-      links:
-        - name: "opsi-webgui"
-          url: "https://gitlab.com/uib/opsiweb-ui/-/jobs/$JOB_ID/artifacts/download"
+# upload:git:
+#   stage: upload
+#   image: registry.gitlab.com/gitlab-org/release-cli:latest
+#   needs:
+#     - job: build:zip
+#       artifacts: true
+#   rules:
+#     - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
+#   script:
+#     - echo "Create Release $TAG, $CI_COMMIT_TAG, $JOB_ID"
+#   release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
+#     tag_name: '$CI_COMMIT_TAG'
+#     description: '$CI_COMMIT_TAG'
+#   release:
+#     name: 'Release $CI_COMMIT_TAG'
+#     tag_name: '$CI_COMMIT_TAG'
+#     ref: '$CI_COMMIT_TAG'
+#     description: 'Release $CI_COMMIT_TAG'
+#     assets:
+#       links:
+#         - name: "opsi-webgui"
+#           url: "https://gitlab.com/uib/opsiweb-ui/-/jobs/$JOB_ID/artifacts/download"
 
 publish:obs_int:
   stage: publish
@@ -701,6 +701,7 @@ publish:obs_ext:
   stage: publish
   dependencies:
     - build:static:app
+    - init:changelogs
   script:
     - *install_tools
     - ./opsi-dev-tool -l debug --obs-update-package https://build.opensuse.org home:uibmz:opsi:4.3:development
